[project]
name = "DeepResearch"
version = "0.0.2.dev0+g92d9435.paveljee"
authors = [
  { name = "Tongyi DeepResearch Team" },
  { name = "Pavel Zhelnov", email = "pzhelnov@p1m.org" }
]

[tool.pixi.workspace]
channels = ["conda-forge"]
platforms = [
  "osx-arm64",
  "linux-64",
  "linux-aarch64"
]

[tool.pixi.tasks]

[tool.pixi.dependencies]
python = "==3.10.0"
